apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  hub: docker.io/istio
  tag: 1.22.2
  profile: default
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
  # Turn on default components: base, pilot, and ingress gateway
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    # Istio Gateway feature
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
#        env:
#          # traffic through this gateway should be routed inside the network
#          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
#            value: network1
        service:
          ports:
            - port: 15021
              targetPort: 15021
              name: status-port
            - port: 15443
              targetPort: 15443
              name: tls
            - port: 3002
              targetPort: 3002
              name: http-custom-1
              protocol: TCP
            - name: tls-istiod
              port: 15012
              targetPort: 15012
            - name: tls-webhook
              port: 15017
              targetPort: 15017
    egressGateways:
    - name: istio-egressgateway
      enabled: false

  # Most default values come from the helm chart's values.yaml
  # Below are the things that differ
  values:
    defaultRevision: ""
    global:
#      network: network1
      istioNamespace: istio-system
      configValidation: true
    gateways:
      istio-ingressgateway: {}
      istio-egressgateway: {}
